select * from person;

create table Person(
	id int generated by default as identity primary key,
	name varchar(100) NOT NULL UNIQUE,
	yearOfBirth int check(yearOfBirth >= 1900)
);

insert into Person(name, yearofbirth) values('Marat M', 1979);
insert into Person(name, yearofbirth) values('Satan S', 1901);

create table Book(
	id int generated by default as identity primary key,
	ownerId int REFERENCES Person(id) ON DELETE SET NULL,
	title varchar NOT NULL,
	author varchar NOT NULL,
	year int check(year >= 0)
);

insert into Book(ownerid, title, author, year) values(null, 'Sobachka', 'Sergej Kuropatkin', 2011);
insert into Book(ownerid, title, author, year) values(null, 'Rasskazy', 'Lev Tolstoj', 1978);


select * from person join book on person.id = ownerid;

select ownerid from book where id=5;

select * from person where id=(select ownerid from book where id=5);